### PR TITLE
Create Dan Rafferty Homepage

### PR DESCRIPTION
**Pull request by rancidcookie**

### CODE REVIEW

**Comment by rancidcookie** [comment]
@htimsneb please review my code.  :)

**Comment by htimsneb** [comment]
Not sure I can approve a Ford Pinto

**Comment by htimsneb** [comment]
...just kidding!

**Comment by rancidcookie** [comment]
@htimsneb  can you assign me to yours so I can see that side?

**Comment by htimsneb** [comment]
@rancidcookie I switched up the assignee/reviewer assignments.  You had me listed as an assignee but I need to be a reviewer to approve

**Pull request merged**
